apiVersion: v1
kind: Pod
metadata: 
  name: grafana
  labels: 
    name: grafana
spec: 
  containers: 
  - name: grafana
    image: my-grafana:v5
    imagePullPolicy: IfNotPresent
    ports: 
    - containerPort: 3000
