apiVersion: v1
kind: Pod
metadata: 
  name: influxdb
  labels: 
    name: influxdb
spec: 
  containers: 
  - name: influxdb
    image: influxdb:latest
    imagePullPolicy: IfNotPresent
    ports: 
    - containerPort: 8086
  tolerations: 
  - operator: "Exists" 
    effect: "NoSchedule"
